{% set name = "TIES20" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UCL-CCS/TIES/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 51354c370ded75886c46695a339a158b6ef474798dd092b5c406826f00138865

build:
  number: 0
  skip: true  # [win or osx and py==310]
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - ties = ties:cli.command_line_script

requirements:
  host:
    - python
    - pip
    - cython
    - setuptools
  run:
    - python
    - ambertools >=21.0
    - matplotlib
    - networkx
    - tabulate
    - MDAnalysis
    - dimod
    - rdkit
    - numpy < 2.3 # see the main environment.yml for the reason

test:
  imports:
    - ties
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - ties --help
    - python -m ties.testing.run

about:
  home: https://github.com/UCL-CCS/TIES20
  summary: Topology Superimposition based on joint graph traversal.
  description: |
    Topology Superimposition based on joint graph traversal.
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://www.ties-service.org/
  dev_url: https://github.com/UCL-CCS/TIES20

extra:
  recipe-maintainers:
    - bieniekmateusz
    - adw62
